[tool.poetry]
name = "django-template"
version = "0.1.0"
description = ""
authors = ["hirowat2 <hiro@estatcamp.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
